## Lab 1: Data in Python

The data for this activity can be downloaded here (under "Data Sets"): https://www.statlearning.com/resources-python

As a first step, create a folder in this location called "data" and drop the Credit.csv file in that location.

If you open the ".gitignore" file, you'll notice that one of the entries is "data" so that your data files will not be shared on GitHub.

In [1]:
import pandas as pd
import numpy as np
Credit = pd.read_csv('data/Credit.csv')
Credit

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance
0,14.891,3606,283,2,34,11,No,No,Yes,South,333
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903
2,104.593,7075,514,4,71,11,No,No,No,West,580
3,148.924,9504,681,3,36,11,Yes,No,No,West,964
4,55.882,4897,357,2,68,16,No,No,Yes,South,331
...,...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,No,No,Yes,South,560
396,13.364,3838,296,5,65,17,No,No,No,East,480
397,57.872,4171,321,5,67,12,Yes,No,Yes,South,138
398,37.728,2525,192,1,44,13,No,No,Yes,South,0
399,18.701,5524,415,5,64,7,Yes,No,No,West,966

### What are the feature names?

In [2]:
feature_names = Credit.columns.tolist()
print(feature_names)

['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Own', 'Student', 'Married', 'Region', 'Balance']

### What are the data types of the feature values (i.e., numeric, categorical)

In [8]:
numeric = ['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Balance']
categorical = ['Own', 'Student', 'Married', 'Region']
print(f'Numeric: {numeric}\nCategorical: {categorical}')

Numeric: ['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Balance']
Categorical: ['Own', 'Student', 'Married', 'Region']

### Find the mean, median, and mode of the feature "Age."

In [4]:
# mean
mean_age = Credit['Age'].mean()
print(mean_age)

55.6675

In [5]:
# median
median_age = Credit['Age'].median()
print(median_age)

56.0

In [7]:
# mode
mode_age = Credit['Age'].mode()
for i in mode_age:
    print(i)

44
66

### Create a subset of Credit that only contains the columns Age, Region, and Income. Call it "Subset."

In [10]:
Subset = Credit[['Age', 'Region', 'Income']]
Subset

     Age Region   Income
0     34  South   14.891
1     82   West  106.025
2     71   West  104.593
3     36   West  148.924
4     68  South   55.882
..   ...    ...      ...
395   32  South   12.096
396   65   East   13.364
397   67  South   57.872
398   44  South   37.728
399   64   West   18.701

[400 rows x 3 columns]

### From this subset, create two partitions: 
- One that contains records for Ages below 50, and one that contains Ages 50+
- Call them "Younger" and "Older"

In [13]:
Younger = Subset[Subset['Age'] < 50]
Younger

     Age Region   Income
0     34  South   14.891
3     36   West  148.924
6     37   East   20.996
9     41   East   71.061
10    30  South   63.095
..   ...    ...      ...
391   43  South   73.327
392   24   West   25.974
394   40  South   49.794
395   32  South   12.096
398   44  South   37.728

[161 rows x 3 columns]

In [14]:
Older = Subset[Subset['Age'] >= 50]
Older

     Age Region   Income
1     82   West  106.025
2     71   West  104.593
4     68  South   55.882
5     77  South   80.180
7     87   West   71.408
..   ...    ...      ...
390   81   West  135.118
393   65   East   17.316
396   65   East   13.364
397   67  South   57.872
399   64   West   18.701

[239 rows x 3 columns]

### Use these partitions to compare the mean and median Income for each age group (less than 50 vs. 50+)

In [17]:
# mean of younger
mean_income_younger = Younger['Income'].mean()
print(mean_income_younger)

41.65203726708074

In [18]:
# mean of older
mean_income_older = Older['Income'].mean()
print(mean_income_older)

47.6216569037657

In [19]:
# median of younger
median_income_younger = Younger['Income'].median()
print(median_income_younger)

31.861

In [21]:
# median of older
median_income_older = Older['Income'].median()
print(median_income_older)

33.694

### What does the difference between mean and median suggest about the distribution of income?

The mean is larger than the median for both the older and younger subset, suggesting the distribution of data is skewed right.

### What are the possible values for Region?

In [23]:
region_vals = Credit['Region'].unique().tolist()
print(region_vals)

['South', 'West', 'East']

### Use the value_counts method to build a frequency table for the possible values of Region.

In [25]:
region_freq = Credit['Region'].value_counts()
region_freq

Region
South    199
West     102
East      99
Name: count, dtype: int64

### Compare the average income for students vs. non-students.

In [ ]:
Students = Credit[Credit['Student'] == 'Yes']
Non_Students = Credit[Credit['Student'] == 'No']
#mean for students
student_mean_income = Students['Income'].mean()
print(student_mean_income)

47.29205

In [ ]:
#mean for non-students
non_student_mean_income = Non_Students['Income'].mean()
print(non_student_mean_income)

44.988533333333336

In [ ]:
#median for students
student_median_income = Students['Income'].median()
print(student_median_income)

33.5655

In [ ]:
#median for non-students
non_student_median_income = Non_Students['Income'].median()
print(non_student_median_income)

32.966499999999996

Often, banks will use a variable called _utilization_ to assess credit risk.
Utilization is the ratio of balance to limit (i.e., what % of the credit limit is being used?)
### Add a feature to the Credit dataset to measure utilization

In [36]:
Credit['Utilization'] = Credit['Balance'] / Credit ['Limit']
Credit

,Income,Limit,Rating,Cards,Age,Education,Own,Student,Married,Region,Balance,Utilization
0,14.891,3606,283,2,34,11,No,No,Yes,South,333,0.092346
1,106.025,6645,483,3,82,15,Yes,Yes,Yes,West,903,0.135892
2,104.593,7075,514,4,71,11,No,No,No,West,580,0.081979
3,148.924,9504,681,3,36,11,Yes,No,No,West,964,0.101431
4,55.882,4897,357,2,68,16,No,No,Yes,South,331,0.067592
...,...,...,...,...,...,...,...,...,...,...,...,...
395,12.096,4100,307,3,32,13,No,No,Yes,South,560,0.136585
396,13.364,3838,296,5,65,17,No,No,No,East,480,0.125065
397,57.872,4171,321,5,67,12,Yes,No,Yes,South,138,0.033086
398,37.728,2525,192,1,44,13,No,No,Yes,South,0,0.000000
399,18.701,5524,415,5,64,7,Yes,No,No,West,966,0.174873

### What is the maximum utilization value in this set?

In [38]:
max_utilization = Credit['Utilization'].max()
print(max_utilization)

0.27693008426326576